version: "2.0"

services: 
  web: 
    build: .
    # command: nodemon --inspect=5858
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5858:5858"


# version: "2"
# services:
#   web:
#     build: .
#     ports:
#       - "3000:3000"
#     links:
#       - mongo
#   mongo:
#     image: mongo
#     volumes:
#       - /data/mongodb/db:/data/db
#     ports:
#       - "27017:27017"